_BASE_: "Base-SemSeg-FPN.yaml"
MODEL:
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  WEIGHTS: 'detectron2://ImageNetPretrained/MSRA/R-101.pkl'
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 101
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "SyncBN"
  SEM_SEG_HEAD:
    NAME: "SemSegFPNHead"
    NUM_CLASSES: 2
    IGNORE_VALUE: 255
DATASETS:
  TRAIN: ("isic2017_train_comb",)
  TEST: ("isic2017_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00005
  STEPS: (60000, 80000)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 250
TEST:
  EVAL_PERIOD: 1000
DATALOADER:
  COPY_PASTE: False
  VISUALIZE_COPY_PASTE: False
  COPY_PASTE_RANDOM_NUM: False
  NUM_WORKERS: 0
  FILTER_EMPTY_ANNOTATIONS: True
OUTPUT_DIR: "seg/output/isic2017-r101-comb"
VERSION: 2